spring.application.name=tttw-amr

spring.datasource.url=jdbc:postgresql://192.168.2.220/phoenix2506
spring.datasource.username=postgres
spring.datasource.password=henge
spring.datasource.driver-class-name=org.postgresql.Driver

# Outbound API URL
outbound.api.url=https://agvtest.free.beeceptor.com/outbound
# Outbound cust code (e.g. TTTW)
amr.companyCode=TTTW
amr.AreaKey= AGV_Area
amr.companyId = 13

#log
log.path=C:/Users/Mei/Documents/Log/AGV
log.maxFileSize=10MB

#Scheduled setting
amr.scheduling.cron0=*/10 * * * * *